### ISSUE TITLE
got exception when trying to create an S3 class according to the readme

### ISSUE THREAD

**Issue by Zxurian** [aws/aws-sdk-php-zf2#29]
```php
$aws = $this->getServiceLocator()->get(Aws::class);
$s3 = $aws->create('S3');
```
results in
```
Catchable fatal error: Argument 2 passed to Aws\Sdk::createClient() must be of the type array, string given, called in /var/www/dev.hub/vendor/aws/aws-sdk-php/src/Sdk.php on line 85 and defined in /var/www/dev.hub/vendor/aws/aws-sdk-php/src/Sdk.php on line 102
Call Stack
#	Time	Memory	Function	Location
1	0.0000	244600	{main}( )	.../index.php:0
2	0.0343	2725840	Zend\Mvc\Application->run( )	.../index.php:17
3	0.0353	2748128	Zend\EventManager\EventManager->trigger( )	.../Application.php:314
4	0.0353	2748128	Zend\EventManager\EventManager->triggerListeners( )	.../EventManager.php:205
5	0.0354	2749888	call_user_func:{/var/www/dev.hub/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:444} ( )	.../EventManager.php:444
6	0.0354	2750384	Zend\Mvc\DispatchListener->onDispatch( )	.../EventManager.php:444
7	0.0363	2837928	Zend\Mvc\Controller\AbstractController->dispatch( )	.../DispatchListener.php:93
8	0.0363	2838392	Zend\EventManager\EventManager->trigger( )	.../AbstractController.php:118
9	0.0364	2838392	Zend\EventManager\EventManager->triggerListeners( )	.../EventManager.php:205
10	0.0377	3023464	call_user_func:{/var/www/dev.hub/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php:444} ( )	.../EventManager.php:444
11	0.0377	3023592	Zend\Mvc\Controller\AbstractActionController->onDispatch( )	.../EventManager.php:444
12	0.0377	3023936	DataSystems\Controller\HooplaController->uploadAction( )	.../AbstractActionController.php:82
13	0.0392	3129432	create ( )	.../HooplaController.php:70
14	0.0392	3129840	Aws\Sdk->__call( )	.../HooplaController.php:70
15	0.0392	3129928	Aws\Sdk->createClient( )
```

**Comment by jeskew** [comment]
The readme was wrong; your second line should read `$s3 = $aws->createS3();` or `$s3 = $aws->createClient('S3');` when working with the currently release of this module.

**Comment by Zxurian** [comment]
tried updating with your code provided, however now I'm getting the following exception:
```
InvalidArgumentException

File:

    /var/www/dev.hub/vendor/aws/aws-sdk-php/src/ClientResolver.php:328

Message:

    Missing required client configuration options: 

    version: (string)

      A "version" configuration value is required. Specifying a version constraint
      ensures that your code will not be affected by a breaking change made to the
      service. For example, when using Amazon S3, you can lock your API version to
      "2006-03-01".
      
      Your build of the SDK has the following version(s) of "s3": * "2006-03-01"
      
      You may provide "latest" to the "version" configuration value to utilize the
      most recent available API version that your client's API provider can find.
      Note: Using 'latest' in a production application is not recommended.
      
      A list of available API versions can be found on each client's API documentation
      page: http://docs.aws.amazon.com/aws-sdk-php/v3/api/index.html. If you are
      unable to load a specific API version, then you may need to update your copy of
      the SDK.

Stack trace:

    #0 /var/www/dev.hub/vendor/aws/aws-sdk-php/src/ClientResolver.php(224): Aws\ClientResolver->throwRequired(Array)
    #1 /var/www/dev.hub/vendor/aws/aws-sdk-php/src/AwsClient.php(137): Aws\ClientResolver->resolve(Array, Object(Aws\HandlerList))
    #2 /var/www/dev.hub/vendor/aws/aws-sdk-php/src/S3/S3Client.php(62): Aws\AwsClient->__construct(Array)
    #3 /var/www/dev.hub/vendor/aws/aws-sdk-php/src/Sdk.php(120): Aws\S3\S3Client->__construct(Array)
    #4 /var/www/dev.hub/module/DataSystems/src/DataSystems/Controller/HooplaController.php(77): Aws\Sdk->createClient('S3')
    #5 /var/www/dev.hub/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(82): DataSystems\Controller\HooplaController->uploadAction()
    #6 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
    #7 /var/www/dev.hub/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #8 /var/www/dev.hub/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #9 /var/www/dev.hub/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(118): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #10 /var/www/dev.hub/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(93): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
    #11 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
    #12 /var/www/dev.hub/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(444): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
    #13 /var/www/dev.hub/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(205): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #14 /var/www/dev.hub/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(314): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
    #15 /var/www/dev.hub/html/index.php(17): Zend\Mvc\Application->run()
    #16 {main}

```

if I go back and add the version key to the aws.local.php then it works, so you may want to update the readme for that as well.
